# Experimental!

# Contains modules `Single` and `Multi` for
# Lenia simulations, for the respective number
# of channels. Each module contains functions
# to run simulations:
#  - `U` updates a world with the given values
#  - `Sim` accumulates frames
Lenia ~ "lenia.ua"

# Contains some presets for creatures:
#  - Orbium
#  - TesselatiumGyrans
#  - Wanderer
#  - Pacman
#  - Fish
#  - Emitter
# 
# Also has ~Pad to pad an array.
Creatures ~ "creatures.ua"